name: Lesson 01 Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for detecting changes

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-disabled: true

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v41
      with:
        since_last_remote_commit: true

    - name: Check if lesson01 files changed
      id: check-lesson01
      run: |
        CHANGED=false

        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          if [[ $file == src/*/kotlin/com/motycka/edu/lesson01/* ]]; then
            CHANGED=true
            break
          fi
        done

        echo "changed=$CHANGED" >> $GITHUB_OUTPUT
        echo "Lesson 01 changed: $CHANGED"

    - name: Run Lesson 01 Tests
      if: steps.check-lesson01.outputs.changed == 'true' || github.event_name == 'workflow_dispatch'
      run: ./gradlew testLesson01
